Feature/mailing list
ZeusWPI/zauth pull request #232
Opened 2022-12-22 23:16 UTC by Tibo-Ulens

fixes #217

2022-12-22 23:18 UTC, redfast00 commented
Ik weet niet echt veel over Zauth, ik denk dat @chvp en @rien hier beter in gaan zijn

2022-12-23 08:14 UTC, rien requested changes
Nice! I've started on this functionality in #223, but you've clearly made more progress here.

Can you add tests for this functionality in order to prevent stuff from breaking in the future?

2022-12-23 08:14 UTC, rien commented on migrations/2022-12-22-205649_add_mails/up.sql
> +-- Your SQL goes here
Is there a specific reason to save sent emails in the database?

2022-12-23 08:14 UTC, rien commented on src/controllers/users_controller.rs
> +#[post("/users/<username>/set_subscribed", data = "<set_subscribed>")]
It would be nice to have a "unsubscribe" button on each email. You could add an `unsubscribe_token` to the user table which can be used to unsubscribe them.

I also think this route can just be merged with the `update_user` route?

2022-12-23 08:14 UTC, rien commented on src/controllers/users_controller.rs
> +	if state_update == UserState::Disabled {
I would either make this implicit (e.g. filtering disabled users from `User::subscribed_users`) or add a validation that ensures disabled users have this field set to `false`.

2022-12-23 08:14 UTC, rien commented on src/mailer.rs
> +			"leden@zeus.ugent.be".parse().map_err(InternalError::from)?,
We might want t add this as a config value?

Also, if all users are already subscribed to the `Leden` mailinglist, won't they receive the email twice?

2022-12-23 08:14 UTC, rien commented on src/models/mail.rs
> +}
If we choose to save mails in the database, we might want to add some validations (e.g. subject and body are not empty and not too long either)

2022-12-23 12:19 UTC, redfast00 commented on src/controllers/users_controller.rs
> +	if state_update == UserState::Disabled {
This was indeed also one of my points for improvements (I think I worded it as 'make it impossible to represent invalid state'). I see it's also handled in the `subscribed_users` function already :)

2022-12-23 13:36 UTC, Tibo-Ulens commented on migrations/2022-12-22-205649_add_mails/up.sql
> +-- Your SQL goes here
@FKD13 mentioned that it would be nice to keep these around for archival reasons. He did specify that this was less important than just having the mailing list functionality but it doesn't add much complexity so i figured it was worth it

2022-12-23 14:40 UTC, FKD13 commented on migrations/2022-12-22-205649_add_mails/up.sql
> +-- Your SQL goes here
Yes, currently mailman has an email archive, which is kinda cool to have. But being able to send them is way more important than having the archive :D

2022-12-23 15:25 UTC, Tibo-Ulens commented on src/controllers/users_controller.rs
> +#[post("/users/<username>/set_subscribed", data = "<set_subscribed>")]
- I added an unsubscribe link to all emails (see 1f843378d8fee3cde5f6b427549ba4fd1d7080a3)
 - see 646eea3dd446b2fd8bd923e6e50f466eb2fdf6fb

2022-12-23 15:32 UTC, Tibo-Ulens commented on src/models/mail.rs
> +}
I added a minimum length of 3 to subject and body, and a max length of 255 to subjects (see cc56de5b7cab034ff5b0139b84608702764872df)

I'm not quite sure what an optimal max length would be for the body though (or subject for that matter) so feel free to change these

2022-12-23 20:18 UTC, Tibo-Ulens commented on src/controllers/users_controller.rs
> +	if state_update == UserState::Disabled {
I removed this in (41745b762d7206617133794a5ee1438f368f3796) as it was no longer necessary due to `User::find_subscribed` filtering for active users

2022-12-23 20:20 UTC, Tibo-Ulens commented
> Nice! I've started on this functionality in #223, but you've clearly made more progress here.
> 
> Can you add tests for this functionality in order to prevent stuff from breaking in the future?

Tests have been added (see b7daa294374acefa1cc6656c624c43b33cf72d3f)

I think that resolves all your requested changes then, but please let me know if i missed something

2022-12-24 11:04 UTC, chvp approved these changes
Code looks good to me; didn't test locally.

2022-12-26 18:37 UTC, rien requested changes
Thanks for the tests :+1: 

There are two points where I'm confused about:
- The unsubscribe token should be usable without being logged in, that is how those tokens usually work (otherwise you would not need a token?)
- Should disabled users still receive mails from the mailing list or not? If so, I would also add a test case where they should be able to unsubscribe themselves.

I see two tests are failing, this should not be the case. Can you find out what causes them to fail?

2022-12-26 18:37 UTC, rien commented on migrations/2022-12-23-143535_add_unsubscribe_token/up.sql
> +ALTER TABLE users ADD COLUMN unsubscribe_token VARCHAR(32) NOT NULL UNIQUE DEFAULT substring(md5(random()::text), 0, 32);
```suggestion
CREATE EXTENSION IF NOT EXISTS pgcrypto;
ALTER TABLE users ADD COLUMN unsubscribe_token VARCHAR(32) NOT NULL UNIQUE DEFAULT translate(encode(gen_random_bytes(24), 'base64'), '+/=', '-_');
```
With this method we get 24 bytes of actual secure randomness (although an unsubscribe token does not have very strict security requirements), but requires the `pgcrypto` extension to be enabled. However this only needs to be done once for the database, hence I added it to the migration.

2022-12-26 18:37 UTC, rien commented on src/controllers/mailing_list_controller.rs
> +	session: AdminSession,
We might want to open up the archive for users?

2022-12-26 18:37 UTC, rien commented on src/controllers/mailing_list_controller.rs
> +	let body = mail.body.clone()
Can you put this in a template?

2022-12-26 18:37 UTC, rien commented on src/mailer.rs
> +			"leden@zeus.ugent.be".parse().map_err(InternalError::from)?,
@Tibo-Ulens can we add this as a config value?

2022-12-26 18:37 UTC, rien commented on src/models/mail.rs
> +	#[validate(length(min = 3))]
```suggestion
	#[validate(length(min = 3, max = 10_000))]
```
Just to have a maximum, I hope if anyone wants to write an email 10 000 chars long, they would consider making a blog post out of it...

2022-12-26 18:37 UTC, rien commented on src/controllers/users_controller.rs
> +	session: UserSession,
It does not really make sense to require a `UserSession` here, what is the use of an unsubscribe token then?

I think the URL with the unsubscribe token should be sufficient to unsubscribe.

2022-12-26 18:37 UTC, rien commented on tests/mailinglist.rs
> +			.body("token=foo")
Where is this token set in the tests? As far as I can see, this does not use the actual unsubscribe token...

2022-12-26 18:37 UTC, rien commented on tests/mailinglist.rs
> +		};
```suggestion
		let test_cfg = common::config();
```
This removes some boilerplate. Is there a specific config value you want to set?

2022-12-26 18:37 UTC, rien commented on tests/mailinglist.rs
> +	("unsubbed01", UserState::Disabled, false),
```suggestion
	("unsubbed0", UserState::Active, false),
	("unsubbed01", UserState::Active, false),
```
From what I've gathered, disabled users should not receive emails (right?) so to test the unsubscribe functionality, the unsubbed users should actually be active I think.

2022-12-26 19:11 UTC, Tibo-Ulens commented on src/mailer.rs
> +			"leden@zeus.ugent.be".parse().map_err(InternalError::from)?,
added in (0107fd13ac901c9f5bb4cfcb37b27c39cbf59bad)

2022-12-26 19:31 UTC, Tibo-Ulens commented on src/controllers/mailing_list_controller.rs
> +	session: AdminSession,
fair enough, changed in (c219822919dab08023f21077dd8e9ed6c9d57a24)

2022-12-26 19:41 UTC, Tibo-Ulens commented on src/controllers/mailing_list_controller.rs
> +	let body = mail.body.clone()
added in (49d7e843184acb6d55625d66ba31131deb12b079)

2022-12-26 19:58 UTC, Tibo-Ulens commented on src/controllers/users_controller.rs
> +	session: UserSession,
This specific route would indeed work fine without requiring a `UserSession`, however the route that renders the actual confirmation form prompting the user to unsubscribe (`users_controller::show_confirm_unsubscribe`) would not.

This route sets the user's unsubscribe token as a hidden field in the confirmation form, but this token is stored in the database in the `users` table and is unique for each user (otherwise we wouldn't know who's unsubscribing).
If this `show_confirm_unsubscribe` route didn't require a session there would be no way to know which token should be set in the form as far as i can tell, you would have to send user-specific data to a user without knowing which user you're dealing with.

So considering the route actually letting the user use this route requires them to be logged in, i don't think there'd be much advantage in making this one not require a session.

I could be missing something here but at the moment i don't see any other way of doing this.

2022-12-26 20:03 UTC, Tibo-Ulens commented on src/controllers/users_controller.rs
> +	session: UserSession,
I just realised this could actually be solved by just prompting the user for their email in the unsubscribe form, would this be an acceptable solution in your opinion?

2022-12-26 20:22 UTC, Tibo-Ulens commented on tests/mailinglist.rs
> +			.body("token=foo")
good catch, should be fixed in (df993a122c69d8ab89dbfcf5fb90b7f5f65af57e)

2022-12-26 20:25 UTC, Tibo-Ulens commented on tests/mailinglist.rs
> +		};
github didn't let me merge the suggestion smh, fixed in (130582595f3e59a78d04e275b52cf40ee18c987d)

2022-12-26 20:29 UTC, Tibo-Ulens commented on tests/mailinglist.rs
> +	("unsubbed01", UserState::Disabled, false),
indeed the should, good catch

2022-12-30 14:18 UTC, rien requested changes
As discussed on mattermost: we want to change how mails are sent by sending a different email to each user (with the unsubscribe token for that user). Users should not be required to sign in to unsubscribe, nor should they give their email.

One test still seems to be failing, should I take a look at it?

2022-12-30 14:18 UTC, rien commented on src/models/mail.rs
> +			id -> Integer,
We might want to save the author of a mail (an admin) and show this on the mail overview page?

2022-12-30 18:40 UTC, Tibo-Ulens commented
> As discussed on mattermost: we want to change how mails are sent by sending a different email to each user (with the unsubscribe token for that user). Users should not be required to sign in to unsubscribe, nor should they give their email.
> 
> One test still seems to be failing, should I take a look at it?

I'd appreciate if you could look at that test, i will be a bit less active after new years so i don't know how quickly i'll get around to it

The changes to unsubscribing and the mailing list have been implemented in (7e596df8302d6911d07078e45fb57966d884eb15), along with reworked tests

I'll try to get around to changing the Mail model to show authors sometime this evening

2022-12-30 20:31 UTC, klaasg commented on src/models/mail.rs
> +pub struct Mail {
Misschien een `sent_to` met userids want de mailinglijst verandert door de tijd?

2022-12-31 14:47 UTC, Tibo-Ulens commented on src/models/mail.rs
> +			id -> Integer,
Added in (888bb1bfee63da45cc1dfc3e8849f9f154a2674b) and (975e9e5b9751d93f235d445e1963971dfacad373)

2022-12-31 14:55 UTC, Tibo-Ulens commented on src/models/mail.rs
> +pub struct Mail {
I'll see if i can add this tomorrow, i have to go consume copious amounts of food for new years right now.

(or you can always try adding it yourself ;))

2022-12-31 15:20 UTC, Tibo-Ulens commented
Adding a scheduling feature to new mails so we can send them at a specific time would probably also be quite nice

2023-03-02 09:10 UTC, rien approved these changes
I have rebased this PR on #241 (and dropped the last commit trying to fix the same issue).

Thanks for the hard work!

2023-03-02 09:10 UTC, merged