Added autocomplete="off" to some password fields
ZeusWPI/zauth pull request #275
Opened 2024-05-23 13:59 UTC by FranseHamburger

2024-05-23 20:26 UTC, redfast00 approved these changes

2024-05-24 09:23 UTC, chvp reviewed
See also: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

2024-05-24 09:23 UTC, chvp commented on templates/session/login.html
> +          <input class="input is-medium" name="password" type="password" placeholder="Password" required autocomplete="off" />
Why would we not want autocomplete when signing in? I think we want to allow people to use password managers?

2024-05-24 09:27 UTC, redfast00 commented on templates/session/login.html
> +          <input class="input is-medium" name="password" type="password" placeholder="Password" required autocomplete="off" />
We got an email from UGent's automated vuln scanner
![image](https://github.com/ZeusWPI/zauth/assets/10746993/20936831-d406-4d79-90cf-6c51a7f08c9a)

2024-05-24 09:29 UTC, redfast00 commented on templates/session/login.html
> +          <input class="input is-medium" name="password" type="password" placeholder="Password" required autocomplete="off" />
After looking at this a bit better; I don't really agree with the vuln scanner, and think the best course of action is emailing DICT to disable those plugins. Another garbage detection as an example: 
![image](https://github.com/ZeusWPI/zauth/assets/10746993/74f74788-49da-4d5e-b0dd-3ee44fe1f6b3)

2024-05-24 09:30 UTC, redfast00 requested changes
Yeah, maybe we shouldn't do this; I think we should email UGent instead

2024-06-19 08:25 UTC, rien commented
I am also against this, as this creates a less secure situation in my option.

2024-06-19 08:25 UTC, closed without merging